---
spring:
  profiles: tertiary
  application:
    name: eureka-server-clustered
server:
  port: 8033
eureka:
  instance:
    hostname: eureka-server-tertiary
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-server-primary:8031/eureka/,http://eureka-server-secondary:8032/eureka/
    
    
